# Generated by Django 4.2.2 on 2023-08-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemabio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='dato',
            field=models.BinaryField(editable=True),
        ),
    ]
