# Generated by Django 4.2.2 on 2023-11-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemabio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_perfil',
            field=models.CharField(choices=[('1', 'Usuario Inquilino'), ('2', 'Usuario Visitante'), ('3', 'Usuario Trabajador')], default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_status',
            field=models.CharField(choices=[('1', 'ALTA'), ('2', 'BAJA')], default='3', max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
