# Generated by Django 4.2.2 on 2023-08-15 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemabio', '0002_alter_sesion_dato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='actualizado',
            new_name='fecha_actualizado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='creado',
            new_name='fecha_creado',
        ),
    ]
