# Generated by Django 4.2.2 on 2023-08-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemabio', '0003_rename_actualizado_usuario_fecha_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='id_tipo_sesion',
            field=models.IntegerField(choices=[('1', 'FACIAL'), ('2', 'VOZ'), ('3', 'HUELLA'), ('4', 'NORMAL')], default='4'),
        ),
    ]
