# Generated by Django 4.2.2 on 2023-08-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemabio', '0004_alter_sesion_id_tipo_sesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_status',
            field=models.CharField(choices=[('1', 'ALTA'), ('2', 'BAJA'), ('3', 'PENDIENTE'), ('4', 'ALTA/COMPLETO')], default='3', max_length=2),
        ),
    ]
