# Generated by Django 4.2.2 on 2023-08-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemabio', '0005_alter_usuario_id_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='id_tipo_sesion',
            field=models.CharField(choices=[('1', 'FACIAL'), ('2', 'VOZ'), ('3', 'HUELLA'), ('4', 'NORMAL')], default='4', max_length=2),
        ),
    ]
